name: nproc

on: push

jobs:
  basic:
    strategy:
      matrix:
        include:
        - os: ubuntu-latest
          command: nproc
        - os: windows-latest
          command: nproc
        - os: macos-latest
          command: sysctl -n hw.physicalcpu
    runs-on: ${{ matrix.os }}
    steps:
    - name: ${{ matrix.command }}
      env:
        os: ${{ matrix.os }}
        command: ${{ matrix.command }}
      shell: bash
      run: |
        (
          echo "# $os"
          echo "## $command"
          $command
        ) | tee -a "$GITHUB_STEP_SUMMARY"
